"""
agent3_report.py - Markdown Report Writing Agent

This module demonstrates how an agent synthesizes outputs from previous agents
and uses XML-structured prompts for formatted output.

How to test standalone:
    python agent3_report.py
"""

import os
import sys
import re

# Add the parent directory to sys.path so we can import from utils.py
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))
from utils import get_groq_client

MODEL = "llama-3.3-70b-versatile"
MAX_TOKENS = 2048

client = get_groq_client()

AGENT3_SYSTEM_PROMPT = """
<role>
You are a professional technical writer creating executive reports for engineering
leaders and job seekers in the AI industry.
</role>

<task>
Synthesize a data summary and strategic insights into a polished Markdown report.
The report should be immediately useful to someone making career decisions.
</task>

<output_format>
Produce a complete Markdown document with EXACTLY these sections:

# [Descriptive Title - include the dataset name and date context]

## Executive Summary
3-4 sentences. The most critical findings and what they mean for the reader.
Must include at least 2 specific numbers from the data.

## Dataset Overview
Brief description of the data: source, size, what it covers, time period if known.

## Key Statistical Findings
Subsections with the most important numbers.
Use tables where comparisons exist (Markdown table format).

## Strategic Insights
Numbered list of 4-6 actionable insights.
Each must include: the finding, the data that supports it, and the recommended action.

## Top Recommendations for AI Job Seekers
3-5 specific, prioritized action items.
Format: **Priority [N]**: [Action] - [Why/Evidence]

## Conclusion
2-3 sentences wrapping up the key message and next steps.

*Report generated by AI Pipeline | Data: [filename]*
</output_format>

<rules>
- Use proper Markdown: ##, ###, **, *, -, |table| syntax.
- Include at least one Markdown table if comparative data exists.
- Be specific - name actual companies, skills, dollar amounts from the data.
- Professional tone - this report should be shareable on LinkedIn or GitHub.
- Do not invent data not present in the summary or insights.
</rules>
"""


def write_report(agent1_result: dict, agent2_result: dict, verbose: bool = False) -> dict:
    """
    Agent 3 main function.

    Args:
        agent1_result: Output dict from agent1_summarize.summarize_csv()
        agent2_result: Output dict from agent2_insights.generate_insights()
        verbose:       Print progress if True

    Returns:
        dict with status, report, word_count, and tokens used
    """
    if agent1_result.get("status") != "success":
        return {"status": "error", "error": "Agent 1 result not valid."}
    if agent2_result.get("status") != "success":
        return {"status": "error", "error": "Agent 2 result not valid."}

    summary = agent1_result["summary"]
    insights = agent2_result["insights"]
    top_opp = agent2_result.get("top_opportunity", "")
    file_name = agent1_result.get("file_name", "dataset")
    row_count = agent1_result.get("row_count", "?")
    numeric_stats = agent1_result.get("raw_stats", {}).get("numeric_stats", "")

    if verbose:
        print(f"Agent 3 Writing report from {file_name} pipeline results...")

    user_message = f"""
Write a professional Markdown report based on the following pipeline outputs.

AGENT 1 OUTPUT (CSV Summary)
File: {file_name} | Rows: {row_count}

{summary}

Key numeric stats (for precise references):
{numeric_stats[:800] if numeric_stats else 'See summary above'}

AGENT 2 OUTPUT (Strategic Insights)

{insights}

Top Opportunity Identified:
{top_opp}

INSTRUCTIONS
Create a professional Markdown report using all the above data.
The primary reader is an engineer in India targeting remote US AI jobs.
Make the recommendations specific and immediately actionable.
"""

    response = client.chat.completions.create(
        model=MODEL,
        max_tokens=MAX_TOKENS,
        messages=[
            {"role": "system", "content": AGENT3_SYSTEM_PROMPT},
            {"role": "user", "content": user_message}
        ]
    )

    report_text = response.choices[0].message.content
    word_count = len(report_text.split())
    heading_count = len(re.findall(r"^#{1,3}\s+", report_text, re.MULTILINE))

    # Handle usage tokens
    usage = getattr(response, "usage", None)
    input_tokens = usage.prompt_tokens if usage else 0
    output_tokens = usage.completion_tokens if usage else 0

    if verbose:
        print(f"Agent 3 Report written: {word_count} words, {heading_count} sections")
        print(f"Agent 3 Tokens -> Input: {input_tokens} | Output: {output_tokens}")

    return {
        "status": "success",
        "report": report_text,
        "word_count": word_count,
        "heading_count": heading_count,
        "tokens": {
            "input": input_tokens,
            "output": output_tokens
        }
    }


# Standalone test
if __name__ == "__main__":
    try:
        from validators import validate_summary, validate_insights, validate_report
    except ImportError:
        validate_summary = None
        validate_insights = None
        validate_report = None
        print("Warning: validators module not found. Validation steps will be skipped.")

    try:
        from agent1_summarize import summarize_csv
    except ImportError:
        print("Error: agent1_summarize.py is required for the standalone test.")
        sys.exit(1)

    try:
        from agent2_insights import generate_insights
    except ImportError:
        print("Error: agent2_insights.py is required for the standalone test.")
        sys.exit(1)

    csv_path = "sample_data.csv"

    print("\nAgent 3 - Report Writing (standalone test)\n")

    print("Running Agent 1...")
    a1 = summarize_csv(csv_path, verbose=True)

    print("\nRunning Agent 2...")
    a2 = generate_insights(a1, verbose=True)

    print("\nRunning Agent 3...")
    a3 = write_report(a1, a2, verbose=True)

    print("\nFinal Report")
    print(a3.get("report", "Error generating report."))

    if validate_report:
        print("\nValidation")
        vr = validate_report(a3.get("report", ""))
        print(vr)
    else:
        print("\nAgent 3 validation skipped.")